version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
    networks:
      - bog-analytics-net
    environment:
      DATABASE_URL: mongodb://mongo:27017
      DATABASE_NAME: bog-analytics

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile.dev
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app
      - ./dashboard/venv:/app/venv
    networks:
      - bog-analytics-net      
      
  example-app:
    build:
      context: .
      dockerfile: example-app/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./example-app:/app
      - /app/node_modules
      - /app/.next

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - bog-analytics-net
    volumes:
      - mongodb-data:/data/db
  
  package-test:
    build:
      context: .
      dockerfile: package/Dockerfile.dev
    volumes:
      - ./package:/app
      - /app/node_modules
    networks:
      - bog-analytics-net
    depends_on:
      - api

networks:
  bog-analytics-net:
    driver: bridge

volumes:
  mongodb-data: