# Use an official Node.js runtime as the base image
FROM node:18.17.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock to the working directory
COPY package/package.json package/yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code to the container
COPY package ./

RUN chmod -R 777 node_modules/

# Start the web app using yarn dev with hot reloading
ENTRYPOINT ["yarn", "test"]
