# Use an official Node.js runtime as the base image
FROM node:18.17.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock to the working directory
# COPY api/package.json api/yarn.lock ./

# Install dependencies
RUN yarn install

RUN chmod -R 777 node_modules/

ENTRYPOINT ["sh", "-c", "rm -rf /tmp/tsx-0 && yarn dev"]